apiVersion: v1
kind: Service
metadata:
  name: example-service-lb
spec:
  selector:
    app: website #anything which has a label of {website}
  ports:
    - port: 80   #leave this default for digital ocean deployment
      targetPort: 8080    # port you exposed while creating image
  type: ClusterIP
